class Words

  def self.list
    default.flatten.shuffle
  end

  def self.default
    [
      %w(jackperrymemorialpark jack perry fair jpmp),
      %w(murdercamp murdercamps murder camp),
      %w(beer beers booze),
      %w(whiskey),
      %w(bang),
      %w(sex),
      %w(trans trangender lgbt),
      %w(smashputt smash putt),
      %w(vest),
      %w(condom condoms),
      %w(consent),
      %w(fishnets),
      %w(tits boobs boob),
      %w(ass butt asses butts),
      %w(crotch dick),
      %w(sectional sectionals),
      %w(shots shot),
      %w(bears),
      %w(respect),
      %w(shit shits),
      %w(pole),
      %w(dance dancers),
      %w(crowd),
      %w(cigarette cigarettes),
      %w(clove cloves),
      %w(drug drugs),
      %w(praisebe),
      %w(jah),
      %w(practice),
      %w(molly xtc),
      %w(shrooms mushrooms fungi),
      %w(lsd acid),
      %w(crowbar crow bar),
      %w(flowberry flowbie),
      %w(hotmess messy hot mess),
      %w(alto altos altosax),
      %w(columbiacity columbia cc),
      %w(lovebomb love bomb lb),
      %w(honk),
      %w(tx texas boston mi seattle wa),
      %w(bellingham olympia),
      %w(coolwhip cool whip),
      %w(fuckoff fuck off),
      %w(fine),
      %w(cock cocks),
      %w(bflat aflat),
      %w(otpisani),
      %w(perrymason),
      %w(getoutdaway),
      %w(crage ratmachine),
      %w(tetris tetfro),
      %w(bumper tracksuit),
      %w(blinkies blinkie),
      %w(cnmc chaotic noise),
      %w(skull skulls),
      %w(black blue silver blackbluesilver),
      %w(pic daypic gigpic),
      %w(bussy thefuckingbus blackbussy black bb),
      %w(they heshethey),
      %w(gig),
      %w(ilikeyou),
      %w(fire flame fires flames),
      %w(waterfront friendsofthewaterfront),
      %w(georgetown gt george),
      %w(scottland boomer),
      %w(sixsixsix),
      %w(baddevil bd),
      %w(baddog nobiscuits),
      %w(cemeterygirls cemetery girls cg),
      %w(colossal),
      %w(dia muerotos diadelosmuertos),
      %w(mountainking mountain king hallofthemountainking),
      %w(hole head headlikeahole nin),
      %w(malaguena),
      %w(mars),
      %w(oolong),
      %w(pinkelephants pink elephants pinkelephantsonparade),
      %w(porque porquetevas ptv),
      %w(sabotage beastieboys),
      %w(sevendawns dawns seven),
      %w(toogoodtoobad good bad),
      %w(docta doctajohn),
      %w(mattie remix),
      %w(log),
      %w(bruiser bruisers),
      %w(trumpet trumpets),
      %w(trombone trombones),
      %w(nado sharknado),
      %w(bro bros),
      %w(sousa sousas sousaphone tuba tubas),
      %w(snare snares),
      %w(quads mids),
      %w(symbals),
      %w(drum drums),
      %w(merch),
      %w(star),
      %w(ma),
      %w(foul),
      %w(greenlake),
      %w(equinox equinoxstudios es),
      %w(diciplinedmayhem mayhem),
      %w(mydarlingsmydoves darlings doves),
      %w(buttdial),
      %w(sgl),
      %w(tenman),
      %w(solo solos),
      %w(onionrings),
      %w(arrange arrangement),
      %w(treble),
      %w(bass),
      %w(clef),
      %w(bee),
      %w(cee),
      %w(dee),
      %w(ef eff),
      %w(gee),
      %w(flat flats),
      %w(sharp sharps),
      %w(accidental accidentals),
      %w(rhythm),
      %w(housing),
      %w(tour),
      %w(detroitpartymarchingband detroit dpmb crash crashdetroit),
      %w(burningman burning man burners),
      %w(solstice solsticeparade),
      %w(letsplay),
      %w(doocracy),
      %w(patch),
      %w(rehearsal),
      %w(steering sc)
    ]
  end

end
